Wyklad 7
mimuw-anki/sik pull request #6
Opened 2021-04-26 16:23 UTC by jmolinski

2021-05-15 13:25 UTC, procrastinationfighter requested changes
Prawie dobrze.

2021-05-15 13:25 UTC, procrastinationfighter commented on wyklady/wyklad7.txt
> +Adresem następnego węzła. Wartość zerowa oznacza siec lokalną.
Literówka (brak polskiego znaku).

2021-05-15 13:25 UTC, procrastinationfighter commented on wyklady/wyklad7.txt
> +To interfejs, który powinien dostarczyć datagram.
Niejednoznaczna składnia:
-Interfejs, który powinien zostać dostarczony przez datagram.
czy
-Interfejs dostarczający datagram

2021-05-28 10:58 UTC, jmolinski commented on wyklady/wyklad7.txt
> +To interfejs, który powinien dostarczyć datagram.
dobra uwaga

2021-05-28 12:17 UTC, procrastinationfighter approved these changes

2021-05-29 08:50 UTC, merged