Wyklad 8
mimuw-anki/sik pull request #7
Opened 2021-05-06 14:02 UTC by jmolinski

2021-05-15 15:10 UTC, procrastinationfighter requested changes
Można było jeszcze dodać coś o różnych algorytmach trasowania, ale nie jest to niezbędne.

2021-05-15 15:10 UTC, procrastinationfighter commented on wyklady/wyklad8.txt
> +ff00::/8 dla IPv6
22 minuta - "drugi oktet może być różny", ale nie wiem jak to interpretować, bo na slajdzie jest ten sam zapis

2021-05-15 15:10 UTC, procrastinationfighter commented on wyklady/wyklad8.txt
> +
Pytanie bez odpowiedzi.

2021-05-15 15:10 UTC, procrastinationfighter commented on wyklady/wyklad8.txt
> +Nie radzi sobie dobrze ze zmianami topologii sieci, wymaga wielu iteracji, jest "gadatliwy" - przesyła dużo informacji
Zmieniłbym formatowanie na wypisanie tych wad w kilku liniach.

2021-05-15 15:10 UTC, procrastinationfighter commented on wyklady/wyklad8.txt
> +W jakich krokach działa algorytm wektora odległoścu?
Literówka.

2021-05-15 17:46 UTC, jmolinski commented on wyklady/wyklad8.txt
> +ff00::/8 dla IPv6
moim zdaniem jest dobrze zapisane - maska `/8` oznacza że liczy się tylko pierwszy oktet `ff`, natomiast `00` musiało się pojawić w zapisie (bo samo ff to byłoby 00ff, coś innego w zapisie bitowym)

2021-05-15 17:47 UTC, jmolinski commented on wyklady/wyklad8.txt
> +
XD

2021-05-15 18:00 UTC, procrastinationfighter commented on wyklady/wyklad8.txt
> +ff00::/8 dla IPv6
Faktycznie, to nie ma problemu.

2021-05-28 11:02 UTC, jmolinski commented on wyklady/wyklad8.txt
> +
Chyba w trakcie robienia zostawiłem to na później bo sam nie umiałem odpowiedzieć xD

2021-05-28 11:05 UTC, jmolinski commented on wyklady/wyklad8.txt
> +
Usuwam to pytanie, one nie mają dobre charakteryzacji chyba, mieszanka dwóch poprzednich pytań

2021-05-28 11:09 UTC, jmolinski commented
> Można było jeszcze dodać coś o różnych algorytmach trasowania, ale nie jest to niezbędne.

Myślałem co można o nich napisać, jednak jedyne co umiałem wydusić to jakieś szczegóły implementacyjne, których nie ma sensu zapamiętywać - trudno ułożyć takie pytania, które dobrze scharakteryzują poszczególne algorytmy trasowania, a nie będą długie/niezapamiętywalne.

2021-05-28 12:17 UTC, procrastinationfighter approved these changes

2021-05-31 22:05 UTC, merged